Ithaca
21 21 22
#####################
# aaaaaaaaaaaaaaaaab#
#    cddeffffffffffb#
#    cddeffffffffffb#
#    cddeffffffffffb#
#ggg-############hhb#
#ggg-  ABCDEFFGH#hhb#
#ggg-       FFIJ#hhb#
#ggg#       KLMJ#hhb#
#ggg#NNNNOOOPQMJ#hhb#
#ggg#NNNNOOOP*RS#hhb#
#ggg#TTTTTUVW**X#hhb#
#ggg#YZ12222W3**#hhb#
#ggg#YZ12222W34*#iib#
#jjj#YZ155555367#klb#
#jjj#############mmb#
#jjjnooooooooooppppb#
#jjjqooooooooooppppb#
#       rrrssssppppb#
#ttttttuvvvvvvvwwwwx#
#####################

